// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woikaziqeqbcidcylmao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvaWthemlxZXFiY2lkY3lsbWFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNjA3ODMsImV4cCI6MjA1NzczNjc4M30.fn-HPDa8rTI-1D_m9R3JnDGHLsZEnUCnaq2v-N13ZAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);